parameters:
#    copy_paste_topic.example.class: CopyPaste\TopicBundle\Example

services:
#    copy_paste_topic.example:
#        class: %copy_paste_topic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
