parameters:
#    copy_paste_front.example.class: CopyPaste\FrontBundle\Example

services:
#    copy_paste_front.example:
#        class: %copy_paste_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
