<?php

namespace MVC\Controller;

require_once dirname(__FILE__) . '/../../controller/Controller.php';

/**
 * Test class for Controller.
 * Generated by PHPUnit on 2012-10-10 at 13:18:53.
 */
class ControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Controller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MVC\Controller\Controller::getControllerDir
     * @todo Implement testGetControllerDir().
     */
    public function testGetControllerDir() {
       global $MVC_Config;
       $MVC_Config['controller']['path'] = "test/dir";
       $dir =  $this->object->getControllerDir();
       $expected = "test/dir";
       $this->assertEquals($dir, $expected);
    }

}

?>
