<?php

namespace MVC\Route;

require_once dirname(__FILE__) . '/../../route/Route.php';

/**
 * Test class for Route.
 * Generated by PHPUnit on 2012-10-10 at 12:08:01.
 */
class RouteTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Route
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Route;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MVC\Route\Route::dispatch
     * @todo Implement testDispatch().
     */
    public function testDispatch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
